# Generated by Django 5.2.8 on 2025-11-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActeDeces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('annee', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('date_deces', models.DateField()),
                ('lieu_deces', models.CharField(max_length=150)),
                ('cause_deces', models.CharField(blank=True, max_length=200, null=True)),
                ('declarant', models.CharField(blank=True, max_length=150, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='actes/deces/pdf/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='actes/deces/qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_verification', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActeMariage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('annee', models.IntegerField()),
                ('epoux_nom', models.CharField(max_length=100)),
                ('epoux_prenom', models.CharField(max_length=100)),
                ('epouse_nom', models.CharField(max_length=100)),
                ('epouse_prenom', models.CharField(max_length=100)),
                ('date_mariage', models.DateField()),
                ('lieu_mariage', models.CharField(max_length=150)),
                ('temoins', models.TextField(blank=True)),
                ('officier', models.CharField(blank=True, max_length=150)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='actes/mariage/pdf/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='actes/mariage/qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=10)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=150)),
                ('nom_mere', models.CharField(max_length=100)),
                ('nom_pere', models.CharField(blank=True, max_length=100, null=True)),
                ('declarant', models.CharField(max_length=100)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='actes/naissances/pdf/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_verification', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_certificat', models.CharField(choices=[('residence', 'Certificat de résidence'), ('celibat', 'Certificat de célibat'), ('mariage', 'Certificat de mariage'), ('hebergement', "Certificat d'hébergement"), ('vie_individuelle', 'Attestation de vie individuelle')], max_length=30)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('motif', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('Validé', 'Validé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('code_verification', models.CharField(max_length=20, unique=True)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='certificats/pdf/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='certificats/qr/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueEtatCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acte_type', models.CharField(choices=[('naissance', 'Naissance'), ('mariage', 'Mariage'), ('deces', 'Décès'), ('certificat', 'Certificat')], max_length=20)),
                ('acte_id', models.IntegerField()),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('code_verification', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Registre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acte', models.CharField(choices=[('naissance', 'Acte de Naissance'), ('mariage', 'Acte de Mariage'), ('deces', 'Acte de Décès'), ('certificat', 'Certificat')], max_length=20)),
                ('annee', models.IntegerField()),
                ('dernier_numero', models.IntegerField(default=0)),
                ('code_verification', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
