# Generated by Django 5.2.8 on 2025-11-20 19:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etat_civil', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='actedeces',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actedeces',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deces_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actemariage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mariage_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actemariage',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mariage_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificat',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='certificat',
            name='validated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cert_validated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiqueetatcivil',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='registre',
            unique_together={('type_acte', 'annee')},
        ),
    ]
