# Generated by Django 5.2.8 on 2025-11-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_civil', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificat',
            name='numero',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
