# Generated by Django 5.2.8 on 2025-11-20 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_civil', '0003_certificat_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historiqueetatcivil',
            name='code_verification',
            field=models.CharField(max_length=20),
        ),
    ]
