# Generated by Django 5.2.8 on 2025-11-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etat_civil', '0005_alter_actenaissance_numero_historiqueverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreMairie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_mairie', models.CharField(max_length=200)),
                ('nom_maire', models.CharField(max_length=150)),
                ('commune', models.CharField(max_length=100)),
                ('departement', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('adresse', models.CharField(blank=True, max_length=250, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('site_web', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mairie/logo/')),
                ('slogan', models.CharField(blank=True, max_length=250, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
